### ISSUE TITLE
Optifine makes Your Quicksand Translucent when Inside

### ISSUE THREAD

**Issue by zachsai** [Moodsss/Quicksand#1]
Title explains it
with optifine
https://i.imgur.com/XZgvnOj.png
without optifine
https://i.imgur.com/DbktA64.png

**Comment by mo0dss** [comment]
could you try optifine h5 pre4?, im not getting any visual issues with that version

**Comment by zachsai** [comment]
Turns out the issue is from fog. If you have fog turned off, it makes it invisible. Anyway you can force the fog?

**Comment by mo0dss** [comment]
Fixed in recent commit
